# Generated by Django 5.1.5 on 2025-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aryaapp', '0002_alter_category_options_karyaseni_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres',
            new_name='Deskripsi',
        ),
        migrations.AddField(
            model_name='order',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
