# Generated by Django 5.1.5 on 2025-02-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryaapp', '0003_rename_addres_order_deskripsi_order_harga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
