# Generated by Django 5.1.5 on 2025-02-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aryaapp', '0004_remove_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
