# Generated by Django 5.1.5 on 2025-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Nomor_HP',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
