# Generated by Django 5.1.5 on 2025-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0002_order_nomor_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proses', models.CharField(max_length=100)),
            ],
        ),
    ]
