# Generated by Django 5.1.5 on 2025-02-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0003_pemesanan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemesanan',
            options={'verbose_name_plural': 'pemesanan'},
        ),
    ]
