# Generated by Django 5.1.5 on 2025-02-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0004_alter_pemesanan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pesan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pemesanan.pemesanan'),
        ),
    ]
